name: Build and Test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y build-essential python-is-python3
      - name: Build the code
        run: make all
      - name: Test the code
        run: make test
